name: electron-secure-defaults Main CI

on:
  push:
    branches: [ "main" ]


#TODO:
#  Add Caching
#  Add toggle for hard fail for vulns
#  Add notification if vulns are found, mark unstable?
#  Parallelize bundle of repo and package for customer

jobs:
  build-and-package:
    name: Build and Package
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: npm install & build
      run: npm install && npm run build
    
    - name: Scan for Vulnerabilities
      continue-on-error: true
      run: npm audit
    - name: Bundle Repo
      run: tar -caf electron-secure-defaults-repo-${{ github.sha }}.zip *

    # Version should be filled in via package.json
    - name: Package for Customer
      run: |
        npm run package
        tar -caf electron-secure-defaults-1.0.0.zip README.md -C package *.exe

    - name: Archive Repo Bundle
      uses: actions/upload-artifact@v3
      with:
        name: Repo Bundle
        path: electron-secure-defaults-repo-${{ github.sha }}.zip

    - name: Archive Customer Package
      uses: actions/upload-artifact@v3
      with:
        name: electron-secure-defaults-1.0.0.zip
        path: electron-secure-defaults-1.0.0.zip
  
    - name: Notify Status
      if: always()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: "ci-notifications" 
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "1pass ${{ job.status }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n${{ github.ref}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Author:*\n${{ github.actor }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n ${{ github.workflow }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*URL:*\n${{ github.server_url }}/${{ github.repository}}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }

      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

